CREATE TABLE internaute (id_internaute INTEGER AUTO_INCREMENT NOT NULL, adresse VARCHAR(255), email VARCHAR(150) NOT NULL UNIQUE, mot_de_passe VARCHAR(255) NOT NULL, nom VARCHAR(100), prenom VARCHAR(100), telephone VARCHAR(20), PRIMARY KEY (id_internaute))
CREATE TABLE produit (id_produit INTEGER AUTO_INCREMENT NOT NULL, description TEXT, disponible TINYINT(1) default 0 NOT NULL, nom VARCHAR(150) NOT NULL, prix DOUBLE NOT NULL, stock INTEGER NOT NULL, id_categorie INTEGER, PRIMARY KEY (id_produit))
CREATE TABLE commande (id_commande INTEGER AUTO_INCREMENT NOT NULL, adresse_livraison VARCHAR(255), date_commande DATETIME, date_paiement DATETIME, mode_paiement VARCHAR(50), montant_total DOUBLE NOT NULL, numero_commande VARCHAR(50) NOT NULL UNIQUE, statut VARCHAR(30), id_internaute INTEGER NOT NULL, PRIMARY KEY (id_commande))
CREATE TABLE ligne_commande (id_ligne INTEGER AUTO_INCREMENT NOT NULL, prix_unitaire DOUBLE NOT NULL, quantite INTEGER NOT NULL, sous_total DOUBLE NOT NULL, id_commande INTEGER NOT NULL, id_produit INTEGER NOT NULL, PRIMARY KEY (id_ligne))
CREATE TABLE categorie (id_categorie INTEGER AUTO_INCREMENT NOT NULL, description TEXT, nom VARCHAR(100) NOT NULL, PRIMARY KEY (id_categorie))
ALTER TABLE commande ADD CONSTRAINT UNQ_commande_0 UNIQUE (numero_commande)
ALTER TABLE ligne_commande ADD CONSTRAINT UNQ_ligne_commande_0 UNIQUE (id_commande, id_produit)
ALTER TABLE produit ADD CONSTRAINT FK_produit_id_categorie FOREIGN KEY (id_categorie) REFERENCES categorie (id_categorie)
ALTER TABLE commande ADD CONSTRAINT FK_commande_id_internaute FOREIGN KEY (id_internaute) REFERENCES internaute (id_internaute)
ALTER TABLE ligne_commande ADD CONSTRAINT FK_ligne_commande_id_produit FOREIGN KEY (id_produit) REFERENCES produit (id_produit)
ALTER TABLE ligne_commande ADD CONSTRAINT FK_ligne_commande_id_commande FOREIGN KEY (id_commande) REFERENCES commande (id_commande)
